ALTER VIEW [dbo].[V_YYSG_SGKC] as
select DW_BM, PZ_ID,PZ_ID as TD_PZ_ID,PZ_MC,PZ_MC as TD_PZ_MC , ZBLX_ID, ZBLX, DJ_ID, DJ_BM, sum(ZL) ZL from(
--收购总量
select DW_BM, PZ_ID, PZ_MC, ZBLX_ID, ZBLX, DJ_ID, DJ_BM, sum(ZL) ZL from (
select DW_BM, 
isnull((select TD_PZ_ID from c_PZTD where SG_PZ_ID= PZ_ID),PZ_ID) PZ_ID, 
isnull((select TD_PZ_MC from c_PZTD where SG_PZ_ID= PZ_ID),PZ_MC) PZ_MC, 
ZBLX_ID, 
ZBLX, 
DJ_ID, 
DJ_BM, 
sum(ZL) ZL from (
SELECT YD_BM AS DW_BM, PZ_ID, PZ_MC, ZBLX_ID, ZBLX, DJ_ID, DJ_BM, sum(ZL) ZL FROM dbo.YYSG_DJBM
WHERE SFSC = 0
group by YD_BM, PZ_ID, PZ_MC, ZBLX_ID, ZBLX, DJ_ID, DJ_BM
union all 
--盘点总量
SELECT A.CD_BM AS DW_BM,B.PZ_ID,B.PZ_MC,B.ZBLXID AS ZBLX_ID,B.ZBLX,DJ_ID,DJ_BM,  sum (B.YKZL) AS ZL FROM YYSG_SYPD AS A 
INNER JOIN YYSG_SYPD_MX AS B ON 
A.SYPD_ID = B.SYPD_ID AND A.SFSC = 0 AND A.SHZT=2 AND B.SFSC = 0 AND B.YKZL <> 0
group by CD_BM, PZ_ID, PZ_MC, B.ZBLXID,B.ZBLX,  DJ_ID, DJ_BM
) a
group by DW_BM, PZ_ID, PZ_MC, ZBLX_ID, ZBLX, DJ_ID, DJ_BM
) a1
group by DW_BM, PZ_ID, PZ_MC, ZBLX_ID, ZBLX, DJ_ID, DJ_BM
union all 
--已打包总量
SELECT YD_BM AS DW_BM,PZ_ID , PZ_MC, ZBLX_ID, ZBLX, DJ_ID, DJ_BM, -ISNULL(SUM(ZL),0) AS ZL
FROM dbo.YYSG_YB WHERE SFSC = 0
GROUP BY YD_BM, PZ_ID, PZ_MC, DJ_ID, DJ_BM, ZBLX_ID, ZBLX
union all
--已锁定总量
SELECT DW_BM,PZ_ID,PZ_MC,ZBLX_ID,ZBLX=ZBLX_MC,DJ_ID,DJ_BM,-ISNULL(SUM(ZL),0) AS ZL FROM YYSG_DBSD WHERE SD_ZT = 1 AND SFSC = 0
GROUP BY DW_BM,PZ_ID,PZ_MC,ZBLX_ID,ZBLX_MC,DJ_ID,DJ_BM) aa

group by DW_BM, PZ_ID, PZ_MC, ZBLX_ID, ZBLX, DJ_ID, DJ_BM


